const weight = { 
    EN: {
        S1: 'Designated operator status',
        S2: 'Brand and tradition',
        S3: 'Good financial condition',
        S4: 'Developed infrastructure',
        S5: "Dominant share in some markets",
        W1: 'Perception, image',  
        W2: 'Poorly developed research base',
        W3: 'Complex organization',
        W4: "Poorly developed marketing",
        W5: 'Quality of Service',
        O1: 'Extension, change of offer',
        O2: "Access to new technologies",
        O3: "Possibility of development and cooperation in the international market",
        O4: "The emergence of new customers",
        O5: 'Availability of specialists in the market',
        T1: 'Changes in market trends',
        T2: 'E-substitution',
        T3: 'Development of current competition',
        T4: "Opportunity for new competition",
        T5: 'Change of legislation'
    },
    PL: {
        S1: 'Status operatora wyznaczonego',
        S2: 'Marka i tradycja',
        S3: 'Dobra kondycja finansowa',
        S4: 'Rozbudowana infrastruktura',
        S5: 'Dominujący udział w niektórych rynkach',
        W1: 'Postrzeganie, wizerunek',
        W2: 'Słabo rozwinięte zaplecze badawczo-rozwojowe',
        W3: 'Złożona organizacja',
        W4: 'Słabo rozwinięty marketing',
        W5: 'Jakość usług',
        O1: 'Rozszerzenie, zmiana oferty',
        O2: 'Dostęp do nowych technologii',
        O3: 'Możliwość rozwoju i współpracy na rynku międzynarodowym',
        O4: 'Pojawienie się nowych grup odbiorców',
        O5: 'Dostępność specjalistów na rynku',
        T1: 'Zmiany trendów rynkowych',
        T2: 'E-substytucja',
        T3: 'Rozwój obecnej konkurencji',
        T4: 'Możliwość pojawienia się nowej konkurencji',
        T5: 'Zmiana regulacji prawnych'
    },
    RU: {
        S1: 'Статус назначенного оператора',
        S2: 'Бренд и традиции',
        S3: 'Хорошее финансовое состояние',
        S4: 'Развитая инфраструктура',
        S5: 'Доминирующая доля на некоторых рынках',
        W1: 'Восприятие, образ',
        W2: 'Недостаточно развитая научно-исследовательская база',
        W3: 'Сложная организация',
        W4: 'Недостаточно развитый маркетинг',
        W5: 'Качество обслуживания',
        O1: 'Расширение, изменение предложения',
        O2: "Доступ к новым технологиям",
        O3: "Возможность развития и сотрудничества на международном рынке",
        O4: 'Появление новых аудиторий',
        O5: 'Доступность специалистов на рынке',
        T1: 'Изменения рыночных тенденций',
        T2: 'Е-замещение',
        T3: 'Развитие текущей конкуренции',
        T4: 'Возможность появления новой конкуренции',
        T5: 'Изменение правового регулирования'
    }
};

